a =float(input("Insira o primeiro número: "))
b =int(input("Insira o segundo número: "))
print(f"Um exemplo de soma dos números: {a+b:.1f}")
print(f"Um exemplo de concatenação de strings: {str(a)+str(b)}")
print(f"Um exemplo da multiplicação dos números: {a*b}")
print(f"Um exemplo da multiplicação como strings: {str(a)*b}")
print(f"Um exemplo da divisão dos números: {a/b}")
print(f"Um exemplo da divisão inteira dos números: {a//b:.1f}")
print(f"Um exemplo de exponenciação {a**b}")
print(f"Um exemplo de módulo (resto): {a%b}")

